### ISSUE TITLE
Can we run this Project at local?

### ISSUE THREAD

**Issue by vxba** [ptc-iot-sharing/BMCollectionView#12]
How can I run this project at localhost to develop and debug etc...
I attempt to run "npm run server" but not able to see any widget UI

**Comment by BogdanMihaiciuc** [comment]
It is not possible to run this project locally. The main purpose of this extension is to act as a bridge between collection view and Thingworx mashups so it doesn't make sense to run it outside of a mashup.

If you are interested in working with the underlying `BMCollectionView` class, you can include `bm-core-ui` as a dependency in your project and import it in either the extension or local project, or both.
