### ISSUE TITLE
Reusing the same BMCollectionViewCell for a new cell with another size does not work

### ISSUE THREAD

**Issue by stefan-lacatus** [ptc-iot-sharing/BMCollectionView#13]
In our application we are driving the sizes of cells via a service. However, even if the UID of the cell is different, when the data is updated and old cells are reused, the cells itself is resized to the new dimensions, but the widgets inside the cell are not resizing automatically to the new size of the cell.

This bug only appears if the cell has widgets that do not resize automatically, like the OOTB charts or the D3RangeChart. This happens because those widgets are rendered to an initial size in `afterRender`, and then expect followup resizes to be driven via the `resize` method.

Attached is a test case. To reproduce (depends on the random data generator):
1. Import all entities [CollectionViewResizeIssue.zip](https://github.com/ptc-iot-sharing/BMCollectionView/files/3906447/CollectionViewResizeIssue.zip)
2. Go to the mashup `CollectionViewResizeIssueTest_MU`
3. Enter an initial size of  400x100 and press Update
4. Enter a size of 400x500. The chart itself properly resizes the first time
5. Enter a size of 400x800. The cell itself resizes, but the chart is only 400x100.

I'd me more than willing to fix this myself, as long as you point me in the right direction

**Comment by stefan-lacatus** [comment]
The issue does not exist when using a BMView in the child cell. That's because View seems to invoke automatically `resize` on the subwidgets (https://github.com/ptc-iot-sharing/BMView/blob/ee7f214dc11355cdc973d448b75834170e725c40/src/BMView.runtime.ts#L53)

**Comment by BogdanMihaiciuc** [comment]
Enable the **HandlesResponsiveWidgets** property when your cell mashups don't use BMView. It is not available in the configuration window so you will need to use the properties panel.

**Comment by stefan-lacatus** [comment]
Indeed, enabling **HandlesResponsiveWidgets** fixes the issue. Thanks!
