### ISSUE TITLE
Collection breaks after rapidly switching between selected data sources 

### ISSUE THREAD

**Issue by Frowne** [ptc-iot-sharing/BMCollectionView#69]
Been forwarded to here, since the issue is seemingly related to BMCollectionView. I realize we're on Thingworx Version 9.5.2 which I presume means we should be using Core Widgets (https://github.com/ptc-iot-sharing/BMCoreUIWidgets), but since I'm using this in a big company setting any extension change has to go through a couple hurdles, so I was hoping for some insight on the current version before having to switch to a different extension altogether.

This is the problem I'm having, I appreciate any and all help with this! 
![Screenshot 2024-08-07 124109](https://github.com/user-attachments/assets/bb37a674-9f61-493a-839b-3083a9aeb955)

**Comment by BogdanMihaiciuc** [comment]
Hello, the current version of this widget should be able to handle this use case.

If you have a local environment where you can test this, once you install this extension, the ootb collection widgets will gain an "upgrade" button that upgrades them to the collection view extension and attempts to retain most of their settings. You can use this to run a quick test and determine if the extension will solve your problem.

**Comment by BogdanMihaiciuc** [comment]
Closing this as it doesn’t seem to apply to this widget, but the ootb one
